//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Dev/GlobalSystem/InputSystem/PlayerController_Action.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController_Action : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController_Action()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController_Action"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""c5eb59f5-33c5-4f61-8235-c9be3586eef0"",
            ""actions"": [
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""936e8e9b-74d0-4117-b3fe-79746200884e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MiddleButtonClick"",
                    ""type"": ""Button"",
                    ""id"": ""3e707039-7357-42ee-8875-9c195f8c8e52"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a73faf6d-9fd6-4b95-9e7b-cfc5efd95462"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""a2e8e707-f79e-4a0f-9080-c632de8805db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftClickHold"",
                    ""type"": ""Button"",
                    ""id"": ""2ada69e3-b415-4725-8159-06e045dee24c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightClickHold"",
                    ""type"": ""Button"",
                    ""id"": ""8bd4e486-eacc-46c3-8146-fa99cd2eefc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MiddleButtonClickHold"",
                    ""type"": ""Button"",
                    ""id"": ""b74638e4-0b32-4b58-8418-304c292e2d8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c456ce1d-18d0-43e2-9453-d67fdfd0622a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""2fe142bc-526e-4e29-b0a6-2a431990ef53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""bae942b2-e1b4-4bf6-b370-a991d86137d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e3ebf1c2-baf8-49c2-994f-56d253dcf1bd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateHorizontal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ce4124d3-6796-43b6-b3e9-0dff33170927"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePositions"",
                    ""type"": ""Value"",
                    ""id"": ""0714b7f8-3cee-4bb0-a14c-70f4fa810f3c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""7e55b07e-64cd-4597-b348-0ff5f9ad09d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""d5559b5f-f6a1-4ce6-b4bf-7d7719ee209e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""d48f9b9b-7df2-4f4f-b715-691ef8b3e6e1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a0d3a54a-4fcd-4763-85e7-119691024a1a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0c632a98-96ad-4076-82a0-acff8bb88c52"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8667baf1-23e7-4584-8abb-b64349f35149"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e0408488-1646-4113-ac25-e72fa006c10c"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1ee73836-533d-4e85-9eb8-2424518909a6"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""41e56188-281f-449a-8f0a-8c33d162ba56"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7f09156f-4e5a-4f48-8c02-54b7ee79430e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ed1ce87d-05db-4a7f-b2b5-134e784665e3"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8fc698e9-88a5-4882-97d3-4c32bf8729c9"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""79d40d36-e569-4a5d-8c3a-c30b83e125c0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a609e145-5278-417b-8b32-8ff98a9ac735"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1a08c939-0d06-495a-81e8-55e9a96d9a48"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b21e051b-f937-4e60-8f26-9325f1e70ffe"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7e595ec4-225c-494e-a8e0-b67ca7f0da79"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""28e6e2ed-f046-4191-8250-34c25adaddad"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6a598e8a-751c-44c9-8c27-4d64b2a85b1f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bed3aed5-95bb-4265-9f61-873c6d071b9d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ec3d44f1-f286-4762-b8d0-4691cef76926"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""26bd470d-25ba-4746-8299-155eb3638c0a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a56c1e49-991e-4a6f-9ec1-f57cd032fb40"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""de2cdf28-a530-4672-8769-24ed660c2ed3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ff86c021-b8a1-48c0-8a7f-9ec47e13b952"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3d8d128a-cc56-4300-9a61-59f8f48bb902"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9f806f45-21fe-47ce-afd4-1311911a92c1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38827b22-74fb-4646-b4dd-872ace0a051d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ec135da-8155-4bc1-a8a2-c3367a1a6c25"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94623f56-cbb9-4b27-8de4-c849c019c3ed"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bc6b6c6-fc18-4ff2-9b92-aeefce8788f7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d824ed8-460e-45e4-905f-4083ec53538e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c05aa3a4-3c97-460b-a597-61c3275c4166"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b74d98ca-93e0-4110-8044-750c083af476"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""794ed667-14ac-4298-879c-621128868d00"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""037e2059-72b9-47aa-bfd4-51b8cfb6dc86"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MousePositions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fbe5535-b095-4afa-91ea-aad6ce43eca7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a5a0afc-ddf9-4f69-b10e-7757e447ad5c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""9529ea39-1598-49b8-a9e2-3de46b23b55a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""9a06b99d-7eec-44ea-a11f-5a0b218d0b37"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""453807a5-887d-4cc8-9636-a4b514cd1679"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""34961e28-d23e-45b2-b5f7-d9ea536dd087"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""885fe4e6-f1f5-405f-a51b-7081aa938dcf"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""853cfa03-9397-4cdd-b411-a3dde8829595"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""cfbf8442-c077-4375-bc7e-565c394c9797"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""80d2e65e-3b53-4ccc-9161-397e3ee3d033"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""6ce17779-a236-4a01-bf6e-0a6ed62203ef"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""53eb05a0-3c34-4f51-8af3-e2a7767efa38"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""NavigateHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4ba79cdf-d6db-44a9-83c2-0d9651424f52"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""LeftClickHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39daf840-704e-4282-bdb0-041f07e2b127"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftClickHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62dd0e88-4520-4a5d-b54b-1cc06115d98f"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8edd24d-96a0-4108-8009-49a4328df2c5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""RightClickHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5c8ed13-1744-4c85-8f90-72b1876ad4ce"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MiddleButtonClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92c624a7-4a36-46a5-a7ef-400ad7bbb213"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MiddleButtonClickHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard and Mouse"",
            ""bindingGroup"": ""Keyboard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_RightClick = m_Game.FindAction("RightClick", throwIfNotFound: true);
        m_Game_MiddleButtonClick = m_Game.FindAction("MiddleButtonClick", throwIfNotFound: true);
        m_Game_ScrollWheel = m_Game.FindAction("ScrollWheel", throwIfNotFound: true);
        m_Game_Click = m_Game.FindAction("Click", throwIfNotFound: true);
        m_Game_LeftClickHold = m_Game.FindAction("LeftClickHold", throwIfNotFound: true);
        m_Game_RightClickHold = m_Game.FindAction("RightClickHold", throwIfNotFound: true);
        m_Game_MiddleButtonClickHold = m_Game.FindAction("MiddleButtonClickHold", throwIfNotFound: true);
        m_Game_Point = m_Game.FindAction("Point", throwIfNotFound: true);
        m_Game_Cancel = m_Game.FindAction("Cancel", throwIfNotFound: true);
        m_Game_Submit = m_Game.FindAction("Submit", throwIfNotFound: true);
        m_Game_Navigate = m_Game.FindAction("Navigate", throwIfNotFound: true);
        m_Game_NavigateHorizontal = m_Game.FindAction("NavigateHorizontal", throwIfNotFound: true);
        m_Game_MousePositions = m_Game.FindAction("MousePositions", throwIfNotFound: true);
        m_Game_Exit = m_Game.FindAction("Exit", throwIfNotFound: true);
        m_Game_RotateCamera = m_Game.FindAction("RotateCamera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private IGameActions m_GameActionsCallbackInterface;
    private readonly InputAction m_Game_RightClick;
    private readonly InputAction m_Game_MiddleButtonClick;
    private readonly InputAction m_Game_ScrollWheel;
    private readonly InputAction m_Game_Click;
    private readonly InputAction m_Game_LeftClickHold;
    private readonly InputAction m_Game_RightClickHold;
    private readonly InputAction m_Game_MiddleButtonClickHold;
    private readonly InputAction m_Game_Point;
    private readonly InputAction m_Game_Cancel;
    private readonly InputAction m_Game_Submit;
    private readonly InputAction m_Game_Navigate;
    private readonly InputAction m_Game_NavigateHorizontal;
    private readonly InputAction m_Game_MousePositions;
    private readonly InputAction m_Game_Exit;
    private readonly InputAction m_Game_RotateCamera;
    public struct GameActions
    {
        private @PlayerController_Action m_Wrapper;
        public GameActions(@PlayerController_Action wrapper) { m_Wrapper = wrapper; }
        public InputAction @RightClick => m_Wrapper.m_Game_RightClick;
        public InputAction @MiddleButtonClick => m_Wrapper.m_Game_MiddleButtonClick;
        public InputAction @ScrollWheel => m_Wrapper.m_Game_ScrollWheel;
        public InputAction @Click => m_Wrapper.m_Game_Click;
        public InputAction @LeftClickHold => m_Wrapper.m_Game_LeftClickHold;
        public InputAction @RightClickHold => m_Wrapper.m_Game_RightClickHold;
        public InputAction @MiddleButtonClickHold => m_Wrapper.m_Game_MiddleButtonClickHold;
        public InputAction @Point => m_Wrapper.m_Game_Point;
        public InputAction @Cancel => m_Wrapper.m_Game_Cancel;
        public InputAction @Submit => m_Wrapper.m_Game_Submit;
        public InputAction @Navigate => m_Wrapper.m_Game_Navigate;
        public InputAction @NavigateHorizontal => m_Wrapper.m_Game_NavigateHorizontal;
        public InputAction @MousePositions => m_Wrapper.m_Game_MousePositions;
        public InputAction @Exit => m_Wrapper.m_Game_Exit;
        public InputAction @RotateCamera => m_Wrapper.m_Game_RotateCamera;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void SetCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterface != null)
            {
                @RightClick.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRightClick;
                @MiddleButtonClick.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMiddleButtonClick;
                @MiddleButtonClick.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMiddleButtonClick;
                @MiddleButtonClick.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMiddleButtonClick;
                @ScrollWheel.started -= m_Wrapper.m_GameActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnScrollWheel;
                @Click.started -= m_Wrapper.m_GameActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnClick;
                @LeftClickHold.started -= m_Wrapper.m_GameActionsCallbackInterface.OnLeftClickHold;
                @LeftClickHold.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnLeftClickHold;
                @LeftClickHold.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnLeftClickHold;
                @RightClickHold.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRightClickHold;
                @RightClickHold.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRightClickHold;
                @RightClickHold.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRightClickHold;
                @MiddleButtonClickHold.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMiddleButtonClickHold;
                @MiddleButtonClickHold.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMiddleButtonClickHold;
                @MiddleButtonClickHold.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMiddleButtonClickHold;
                @Point.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPoint;
                @Cancel.started -= m_Wrapper.m_GameActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnCancel;
                @Submit.started -= m_Wrapper.m_GameActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnSubmit;
                @Navigate.started -= m_Wrapper.m_GameActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnNavigate;
                @NavigateHorizontal.started -= m_Wrapper.m_GameActionsCallbackInterface.OnNavigateHorizontal;
                @NavigateHorizontal.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnNavigateHorizontal;
                @NavigateHorizontal.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnNavigateHorizontal;
                @MousePositions.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePositions;
                @MousePositions.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePositions;
                @MousePositions.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePositions;
                @Exit.started -= m_Wrapper.m_GameActionsCallbackInterface.OnExit;
                @Exit.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnExit;
                @Exit.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnExit;
                @RotateCamera.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRotateCamera;
            }
            m_Wrapper.m_GameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @MiddleButtonClick.started += instance.OnMiddleButtonClick;
                @MiddleButtonClick.performed += instance.OnMiddleButtonClick;
                @MiddleButtonClick.canceled += instance.OnMiddleButtonClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @LeftClickHold.started += instance.OnLeftClickHold;
                @LeftClickHold.performed += instance.OnLeftClickHold;
                @LeftClickHold.canceled += instance.OnLeftClickHold;
                @RightClickHold.started += instance.OnRightClickHold;
                @RightClickHold.performed += instance.OnRightClickHold;
                @RightClickHold.canceled += instance.OnRightClickHold;
                @MiddleButtonClickHold.started += instance.OnMiddleButtonClickHold;
                @MiddleButtonClickHold.performed += instance.OnMiddleButtonClickHold;
                @MiddleButtonClickHold.canceled += instance.OnMiddleButtonClickHold;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @NavigateHorizontal.started += instance.OnNavigateHorizontal;
                @NavigateHorizontal.performed += instance.OnNavigateHorizontal;
                @NavigateHorizontal.canceled += instance.OnNavigateHorizontal;
                @MousePositions.started += instance.OnMousePositions;
                @MousePositions.performed += instance.OnMousePositions;
                @MousePositions.canceled += instance.OnMousePositions;
                @Exit.started += instance.OnExit;
                @Exit.performed += instance.OnExit;
                @Exit.canceled += instance.OnExit;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
            }
        }
    }
    public GameActions @Game => new GameActions(this);
    private int m_KeyboardandMouseSchemeIndex = -1;
    public InputControlScheme KeyboardandMouseScheme
    {
        get
        {
            if (m_KeyboardandMouseSchemeIndex == -1) m_KeyboardandMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and Mouse");
            return asset.controlSchemes[m_KeyboardandMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IGameActions
    {
        void OnRightClick(InputAction.CallbackContext context);
        void OnMiddleButtonClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnLeftClickHold(InputAction.CallbackContext context);
        void OnRightClickHold(InputAction.CallbackContext context);
        void OnMiddleButtonClickHold(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnNavigate(InputAction.CallbackContext context);
        void OnNavigateHorizontal(InputAction.CallbackContext context);
        void OnMousePositions(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
    }
}
